#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       you could run this script as: bash gradlew
#       POSIX shells will apply word splitting, if unquoted variables are used.
#
#   (2) Is necessary for `linux` and `macosx` systems where run-time discovery
#       of Java needs to be improved.
#
#   (3) This is unused - b/c the "for" loop in runScripts as the only
#       delimiter.
#
#       * Want to require a certain Java version for the wrapper to work?
#         Use GRADLE_REQUIRE_JAVA_VERSION.
#       * When classification of Gradle and Java version is changed, it is not
#         refreshing the Gradle Dame. Check $HOME/.gradle/daemon on Unix-like
#         systems or on Windows.
#
#   (4) Instance of shell is created for the wrapper script, as a background
#       process, without output or blocking until it exits.
#
#   (5) The exit status of this script is that of the last exec() in the script.
#       If no commands are executed before the script exits, the exit status will be "0".
#
##############################################################################

set -e

PRG="$0"

while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done

SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

if [ -z "$GRADLE_WRAPPER_DEBUG" ] ; then
    GRADLE_WRAPPER_DEBUG=false
fi

if [ -n "$JAVA_OPTS" ] ; then
    GRADLE_OPTS="$GRADLE_OPTS $JAVA_OPTS"
fi

# Collect all arguments for the java command, stacking in reverse order
BUILD_JAVA_OPTS=""
for arg in "$@" ; do
    BUILD_JAVA_OPTS="$arg $BUILD_JAVA_OPTS"
done

exec "$JAVACMD" $BUILD_JAVA_OPTS \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
